### ISSUE TITLE
The location of standard file

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#17]
Having a discussion with @onbit-syn, we found some problems with having the standard file in our application as well as inside this repository:

1. How would we be able to read this file in a browser?
2. The standard file will have to be updated frequently, then how would we be able to present those changes to use diff library without publishing another version of this library.

Also, we wanted to have our user provide their own standard file, either through a URL or a file.

So, to overcome these problems, we have thought of an approach:

**Have the standard file hosted somewhere else, and let our library fetch it when it is invoked**.

We will just provide our library with a default URL of the standard file, which it will fetch when generating the diff. It will overcome the problem of updating the library, because we can just update the standard file, and our library will fetch it during its usage.

This approach will also be best suited in browser environments as well.

What are your thoughts on it?

**Comment by derberg** [comment]
we should definitely not go with URL approach, or an approach that file must be read from a file system, because this way diff generation performance would be affected either by latency of the network while fetching, or the operating system when reading the file. 

when talking about standard, do we have to say `standard file`, like basically that it is json or yml file only? Can it be more flexible?

you are working on a lightweight library here, so as you mentioned, it should be easy to use in node and browser. 

why not just talk about `standard` that of course you represent with json or yml, but in the end you pass it to the library as a string (when you want to customize)?

so by default, the standard is "hardcoded" in a `js` file, but you can override by passing a stringified json to the library.

as simple as that. Then it is up to the UI (AsyncAPI Studio) or AsyncAPI CLI to facilitate more options, like that user can pass a link to the file like for example `asyncapi diff --config /my/path/to/mystandard.json` and CLI will be responsible for parsing the json file and passing it as a string to the library.

does it make sense? thoughts?

**Comment by magicmatatjahu** [comment]
I agree what Łukasz said. Also as you remember (or not 😅 ) I wrote in one comment in another issue that you should treat the standard file as JS object, not file, but I also see the utility to have standard in the file.

For that we can write the standard in the `json` file and then make simple bash script to convert the normal `json` to the `JS object` in js file, something like:

```js
// standard.json
{
  ...
}

// standard.js
const STANDARD = {
 ...
}
```

and then you will have `json` and operate in the code on the `js` object. You can also use for it the `rollup` or another bundler.

> The standard file will have to be updated frequently, then how would we be able to present those changes to use diff library without publishing another version of this library.

Why do you want to do that? If standard file will be updated we should also publish the `diff` package because we should also export the standard file from package - for merge user's standard.

Also remember that you can include the `json` file in the package which will be pushed to the npm and then we can also host this file from https://unpkg.com (check example of our ParserJS - https://unpkg.com/@asyncapi/parser@latest/dist/bundle.js).

**Comment by aayushmau5** [comment]
hmm, yeah. I agree with the points that @derberg presented. Having the standard as an object will be better as compared to having it inside a JSON file and reading it.

@magicmatatjahu Interesting idea, and I will certainly look into it. But I'm not sure about the benefits/drawbacks we will have by adding a step of converting JSON to JS object, as compared to having the standard "hard-coded" inside a JS file.

**Comment by derberg** [comment]
> For that we can write the standard in the json file and then make simple bash script to convert the normal json to the JS object in js file

doable, but ads complexity that I don't think is needed at this stage

**Comment by magicmatatjahu** [comment]
Don't worry, we can add this if someone will need the normal JSON file.

**Comment by aayushmau5** [comment]
I guess for now, I'm going to put these standards inside the library as an object. Then, if need be, we can go with putting in JSON file as well. How about that?

**Comment by onbit-syn** [comment]
Sorry, all (@derberg @magicmatatjahu @aayushmau5 ) for the late reviews.
I agree with @derberg fetching `standard` file from the URL will no doubt decrease the performance of the library.

> Why do you want to do that? If standard file will be updated we should also publish the diff package because we should also export the standard file from package - for merge user's standard.

@magicmatatjahu We want to do this because the `Async API Schema` may change in the future, and in that case, we'd have to release a new package just to accommodate new changes (or just to update the standard), whereas if we store the standard in a central repository and access it via a URL, we won't have to release a new version of the `diff` library.

Just the thoughts. Please correct me where I am wrong.

**Comment by derberg** [comment]
you would anyway have to version the standard, if accessed via URL, you would have to have /v1, /v2 or something similar in the URL and basically it would mean manual change in the library anyway. Releasing of `diff` with a new URL would have to happen anyway.

**Comment by magicmatatjahu** [comment]
The `standard` file hosted in website will be only needed for the packages which will be written in other than JS languages. As I wrote in previous comment, we can do it if someone will need it, but I think that probably only we will use this standard (in this package) and maybe other Github Organisations like Stoplight, but they also write core tools in the JS, so I don't see any problems with current approach.
