### ISSUE TITLE
Include underlying TypeScript types into the API Documentation

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/diff#47]
The current [API Documentation](https://github.com/asyncapi/diff/blob/master/API.md), which is generated automatically using `jsdoc2md`, doesn't include the underlying types.
For example,
![image](https://user-images.githubusercontent.com/54525741/135437616-dea1e7aa-0fc1-4843-a73b-2aaf4133bb01.png)

It is not clear what the `DiffOutputItem` "looks" like.

**The reason:**

JSDoc2md does not include TypeScript types when it looks into JSDoc comments, or rather, It doesn't find the typescript types when generating the documentation.

**Request:**

We want the underlying TypeScript types to be present inside the auto-generated API documentation. 

The output will depend on how `jsdoc2md` parses the types. One can look into `jsdoc2md` documentation to see how to parse the TypeScript types :)

**Comment by Ishmam156** [comment]
Thank you! Will definitely do reach out if I struggle with it - will try to provide an overall response by this weekend :)

**Comment by ron-debajyoti** [comment]
@Ishmam156 are you still trying to solve this? If not I would like to take a shot at it as well, if that's fine with you @aayushmau5

**Comment by aayushmau5** [comment]
@ron-debajyoti sure, go ahead. Though I did try to fix this issue, but I did not succeed, and to be honest, I don't think this can be done without more configuration and including additional JSDoc comments. 
But feel free to give your take, and see what you can come up with. Otherwise I will close this issue.

**Comment by ron-debajyoti** [comment]
> But feel free to give it a try, and see what you can come up with. Otherwise, I will close this issue.
Give me 2 days nad I will update the status by then @aayushmau5

**Comment by Ishmam156** [comment]
@ron-debajyoti Thank you so much for taking this up! I honestly tried following the current instructions of JSDoc but just couldn't get this to work - ofcourse might have missed something so good luck to you! :)

**Comment by ron-debajyoti** [comment]
Hey @aayushmau5 ,
I was looking into this and idk maybe this might be leading somewhere and thought to give you an update.

I think one root cause for this problem is that the compiled js obtained after build/tsc can't resolve types. You can try it out yourself by first running the build and then checking out any `jsdoc` comments in  `lib/asyncapidiff.js`, for example, and they point to unresolved/any.

To solve this I changed the syntax of `jsdoc` comments. Taking the above example, I tried changing ` @returns {Array<DiffOutputItem>}` to ` @returns {Array<import('./types').DiffOutputItem>} ` in  `src/asyncapidiff.ts`. This solves the above problem, but then jsdoc2md got issues parsing this tag. 

I'm still gonna try looking into it. Let me know your views on this.
